.NET 6
Zaitonn/Serein pull request #5
Opened 2022-06-08 18:31 UTC by StarsDream00

2022-06-09 04:24 UTC, Zaitonn commented on Program.cs
> +                _ = Directory.CreateDirectory(Global.Path + "\\logs\\crash");
（没必要这样写，按原来的就行了

2022-06-09 04:24 UTC, Zaitonn commented on Ui/Ui_Plugin.cs
> +                Arguments = PluginList.SelectedItems.Count >= 1
不要用太长的三元运算符

2022-06-09 04:25 UTC, Zaitonn commented on Program.cs
> +                _ = Directory.CreateDirectory(Global.Path + "\\logs\\crash");
其他的也一起改一下吧 格式统一

2022-06-09 04:45 UTC, Zaitonn commented
net的版本选5.x

2022-06-09 04:45 UTC, StarsDream00 commented
> net的版本选5.x

为什么

2022-06-09 05:13 UTC, Zaitonn commented
> > net的版本选5.x
> 
> 为什么

算了那也行

2022-06-09 10:06 UTC, StarsDream00 commented
> 顺便请教一下，为什么用net6编译出来是散装的，而原来4.7.2不会👉🏻👈🏻

迁移时自动加了几个Nuget包

2022-06-09 15:03 UTC, StarsDream00 commented
不是，都return了还干嘛else……

2022-06-09 15:10 UTC, Zaitonn requested changes
![image](https://user-images.githubusercontent.com/103164490/172879003-da4507e6-fc75-45d9-aa89-75e6b386d4a9.png)

个人感觉还是用net4.7.2的好，毕竟是win10自带的库也比较方便，所以还请麻烦改一下

2022-06-09 15:10 UTC, StarsDream00 commented
> ![image](https://user-images.githubusercontent.com/103164490/172879003-da4507e6-fc75-45d9-aa89-75e6b386d4a9.png)
> 
> 个人感觉还是用net4.7.2的好，毕竟是win10自带的库也比较方便，所以还请麻烦改一下

详见 https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-6/

2022-06-09 15:42 UTC, Zaitonn commented
> > ![image](https://user-images.githubusercontent.com/103164490/172879003-da4507e6-fc75-45d9-aa89-75e6b386d4a9.png)
> > 个人感觉还是用net4.7.2的好，毕竟是win10自带的库也比较方便，所以还请麻烦改一下
> 
> 用.NET 6.0的原因详见 https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-6/ 部分情况下.NET 6能比.NET 4快100倍 而且你这没装.NET 6.0桌面运行时吧

是的没装，但是我的意思是出于方便发布和使用考虑，本身是想弄成一般下载即可使用而不需要另外装运行库👉👈
而且……
```
已启动生成...
------ 已启动生成: 项目: Serein, 配置: Debug Any CPU ------
C:\Users\Administrator\Desktop\Serein-main (1)\Serein-main\Ui\GetInfo.cs(99,39,99,61): warning SYSLIB0014: “WebRequest.Create(string)”已过时:“WebRequest, HttpWebRequest, ServicePoint, and WebClient are obsolete. Use HttpClient instead.”
C:\Users\Administrator\Desktop\Serein-main (1)\Serein-main\baseFunction\Server.cs(286,13,286,38): warning SYSLIB0006: “Thread.Abort()”已过时:“Thread.Abort is not supported and throws PlatformNotSupportedException.”
C:\Users\Administrator\Desktop\Serein-main (1)\Serein-main\baseFunction\Server.cs(322,13,322,39): warning SYSLIB0006: “Thread.Abort()”已过时:“Thread.Abort is not supported and throws PlatformNotSupportedException.”
C:\Users\Administrator\Desktop\Serein-main (1)\Serein-main\baseFunction\Server.cs(332,13,332,41): warning SYSLIB0006: “Thread.Abort()”已过时:“Thread.Abort is not supported and throws PlatformNotSupportedException.”
MSBUILD : warning FodyPackageReference: Fody: The package reference for Costura.Fody is missing the 'compile' part in the IncludeAssets setting; it's recommended to completely remove IncludeAssets
Serein -> C:\Users\Administrator\Desktop\Serein-main (1)\Serein-main\bin\Debug\net6.0-windows\Serein.dll
已完成生成项目“Serein.csproj”的操作。
========== “生成”: 1 成功，0 失败，0 更新，0 已跳过 ==========
```
会崩

2022-06-09 15:45 UTC, StarsDream00 commented
> > > ![image](https://user-images.githubusercontent.com/103164490/172879003-da4507e6-fc75-45d9-aa89-75e6b386d4a9.png)
> > > 个人感觉还是用net4.7.2的好，毕竟是win10自带的库也比较方便，所以还请麻烦改一下
> > 
> > 
> > 用.NET 6.0的原因详见 https://devblogs.microsoft.com/dotnet/performance-improvements-in-net-6/ 部分情况下.NET 6能比.NET 4快100倍 而且你这没装.NET 6.0桌面运行时吧
> 
> 是的没装，但是我的意思是出于方便发布和使用考虑，本身是想弄成一般下载即可使用而不需要另外装运行库👉👈 而且……
> 
> ```
> 已启动生成...
> ------ 已启动生成: 项目: Serein, 配置: Debug Any CPU ------
> C:\Users\Administrator\Desktop\Serein-main (1)\Serein-main\Ui\GetInfo.cs(99,39,99,61): warning SYSLIB0014: “WebRequest.Create(string)”已过时:“WebRequest, HttpWebRequest, ServicePoint, and WebClient are obsolete. Use HttpClient instead.”
> C:\Users\Administrator\Desktop\Serein-main (1)\Serein-main\baseFunction\Server.cs(286,13,286,38): warning SYSLIB0006: “Thread.Abort()”已过时:“Thread.Abort is not supported and throws PlatformNotSupportedException.”
> C:\Users\Administrator\Desktop\Serein-main (1)\Serein-main\baseFunction\Server.cs(322,13,322,39): warning SYSLIB0006: “Thread.Abort()”已过时:“Thread.Abort is not supported and throws PlatformNotSupportedException.”
> C:\Users\Administrator\Desktop\Serein-main (1)\Serein-main\baseFunction\Server.cs(332,13,332,41): warning SYSLIB0006: “Thread.Abort()”已过时:“Thread.Abort is not supported and throws PlatformNotSupportedException.”
> MSBUILD : warning FodyPackageReference: Fody: The package reference for Costura.Fody is missing the 'compile' part in the IncludeAssets setting; it's recommended to completely remove IncludeAssets
> Serein -> C:\Users\Administrator\Desktop\Serein-main (1)\Serein-main\bin\Debug\net6.0-windows\Serein.dll
> 已完成生成项目“Serein.csproj”的操作。
> ========== “生成”: 1 成功，0 失败，0 更新，0 已跳过 ==========
> ```
> 
> 会崩

这是因为你用了被弃用的方法
现在用的是Task+CancellationTokenSource

2022-06-10 04:19 UTC, Zaitonn reviewed
这几个地方其实没必要改成task吧 ~~毕竟不用abort~~
顺便请教一下，如果task执行完不管他是不是也没啥问题（就是说是不是没必要cancel掉

2022-06-10 15:18 UTC, merged

2022-06-11 04:51 UTC, Zaitonn commented
出于方便考虑我可能还是会把版本降回去……您所说的速度更快目前来看暂时没什么影响……不好意思哈orz

2022-06-11 07:01 UTC, StarsDream00 commented
> 出于方便考虑我可能还是会把版本降回去……您所说的速度更快目前来看暂时没什么影响……不好意思哈orz

你知道有多平台编译吗，，

2022-06-11 10:44 UTC, Zaitonn commented
> > 出于方便考虑我可能还是会把版本降回去……您所说的速度更快目前来看暂时没什么影响……不好意思哈orz
> 
> 你不知道有多版本编译吗，，

请问怎么弄👀

2022-06-11 11:29 UTC, Zaitonn commented
![761F8725-0C45-410C-8B84-A36352F1A7A4](https://user-images.githubusercontent.com/103164490/173186004-fb9a08f1-62d9-49a0-9ee6-ec68e22d94e3.png)
这咋办

2022-06-11 12:32 UTC, StarsDream00 commented
> > > 出于方便考虑我可能还是会把版本降回去……您所说的速度更快目前来看暂时没什么影响……不好意思哈orz
> > 
> > 
> > 你不知道有多版本编译吗，，
> 
> 请问怎么弄👀

https://docs.microsoft.com/zh-cn/dotnet/core/porting/project-structure

2022-06-11 12:33 UTC, StarsDream00 commented
> ![761F8725-0C45-410C-8B84-A36352F1A7A4](https://user-images.githubusercontent.com/103164490/173186004-fb9a08f1-62d9-49a0-9ee6-ec68e22d94e3.png) 这咋办

csproj没改对，它都写出来了

2022-06-12 05:22 UTC, Zaitonn commented
谢谢，这个解决了
但是再请教一下
```
2022/6/12 13:02:57  |  v1.2.3
System.Resources.MissingManifestResourceException: 未能找到任何适合于指定的区域性或非特定区域性的资源。请确保在编译时已将“Serein.Ui.resources”正确嵌入或链接到程序集“Serein”，或者确保所有需要的附属程序集都可加载并已进行了完全签名。
   在 System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   在 System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   在 System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   在 System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   在 System.Resources.ResourceManager.GetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   在 System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   在 System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   在 System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   在 System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   在 System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   在 System.ComponentModel.ComponentResourceManager.ApplyResources(Object value, String objectName, CultureInfo culture)
   在 Serein.Ui.InitializeComponent()
   在 Serein.Ui..ctor()
   在 Serein.Program.Main()
===============================================
```
这个是咋了

2022-06-12 05:36 UTC, StarsDream00 commented
> System.Resources.MissingManifestResourceException

https://docs.microsoft.com/zh-cn/dotnet/api/system.resources.missingmanifestresourceexception?view=net-6.0

2022-06-12 05:36 UTC, StarsDream00 commented
> 谢谢，这个解决了，可以编译了 但是再请教一下 运行4.7.2的会报错但是6.0不会是为什么
> 
> ```
> 2022/6/12 13:02:57  |  v1.2.3
> System.Resources.MissingManifestResourceException: 未能找到任何适合于指定的区域性或非特定区域性的资源。请确保在编译时已将“Serein.Ui.resources”正确嵌入或链接到程序集“Serein”，或者确保所有需要的附属程序集都可加载并已进行了完全签名。
>    在 System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
>    在 System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
>    在 System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
>    在 System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
>    在 System.Resources.ResourceManager.GetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
>    在 System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
>    在 System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
>    在 System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
>    在 System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
>    在 System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
>    在 System.ComponentModel.ComponentResourceManager.ApplyResources(Object value, String objectName, CultureInfo culture)
>    在 Serein.Ui.InitializeComponent()
>    在 Serein.Ui..ctor()
>    在 Serein.Program.Main()
> ===============================================
> ```
> 
> 这个是咋了

https://docs.microsoft.com/zh-cn/dotnet/api/system.resources.missingmanifestresourceexception?view=net-6.0

2022-06-12 05:37 UTC, StarsDream00 commented
要懂得查doc

2022-06-12 16:08 UTC, Zaitonn commented
> 

谢了 加了一行就搞定了
https://github.com/Zaitonn/Serein/blob/380a622cd96416a79419079a01e3a5e414a111c0/Serein.csproj.user#L72